### ISSUE TITLE
Online Instance Doesn't Load

### ISSUE THREAD

**Issue by cibersheep** [dark-eye/pixelfed-web#3]
I have chosen several instances and they seem not to load.
Sometimes choosing another instance keeps loading without showing and instance.

This happens on wi-fi and on 3g.

http://paste.ubuntu.com/p/8zBw9HNsH8/

**Comment by dark-eye** [comment]
@cibersheep It should now notify you when it failed fetching the instances  lists (my guess on why  it  was stuck before :) ).

please notify me  If you have the  time  and this  issue return 
Thanks for the  help :+1:

**Comment by cibersheep** [comment]
I saw your update, thank you for your work but federated.photos seems not to load: Restart button shows and that's it.
On Morph the instance loads correctly

http://paste.ubuntu.com/p/2DSBYGGjJw/

**Comment by dark-eye** [comment]
Ok found the issue, A fix will be in the next update 

thanks for the help  :+1:

**Comment by cibersheep** [comment]
Good news :)
Thank you
