### ISSUE TITLE
Consider Following HIG Colors

### ISSUE THREAD

**Issue by cibersheep** [dark-eye/pixelfed-web#4]
Obviously, you can design your app to your liking but consider following the [color semantics](https://gitlab.com/ubports/teams/ux-des/ubuntu-touch-human-interface-guidelines---hib/wikis/Layout/05-Dialogues) from the system:

i.e. "Choose another instance" is a red button which is read as a destructive (aka irreversible) action (which I would say it is no :))

**Comment by dark-eye** [comment]
@cibersheep  good idea thanks
