### ISSUE TITLE
After an Instance Is Loaded There Is no Way to Choose Another

### ISSUE THREAD

**Issue by cibersheep** [dark-eye/pixelfed-web#5]
After one instance is loaded, you need to close and reopen the app to choose a different instance

**Comment by dark-eye** [comment]
@cibersheep you can change the instance in the bottomedge menu ("change pod" action in the hamburger menu)

**Comment by cibersheep** [comment]
Oh... normally the BottomEdge shows a «hint», that's why I didn't find it :P

**Comment by dark-eye** [comment]
Yay i faded it  out a little as it clashes with the pixelfed design i might need to add some opacity...
