### ISSUE TITLE
Adding custom address not working with https?

### ISSUE THREAD

**Issue by poVoq** [dark-eye/pixelfed-web#7]
I tried to connect to a custom address as indicated in the search input field of the instance chooser, but this doesn't have any effect. 

It seems to recognize that I am inputting an URL, when I type `https://example.com/` but pressing the enter key on the keyboard just results in a blank page.

Edit: it seems to work only with `http` not with `https`.

Strangly though if I put the http adress it loads the desktop version of the pixelfed page and not the mobile one.

I am using the Ubports dev channel on a Nexus5.

**Comment by poVoq** [comment]
The main problem is definitely the automatic triggering of search() here:
https://github.com/dark-eye/pixelfed-web/blob/master/qml/pages/InstancePicker.qml#L163
as search() also includes the looking for the "http" part in the string and triggers automatically the custom instance even if the user has not finished typing the URL.

But is also seems the "http" interrupt here: https://github.com/dark-eye/pixelfed-web/blob/master/qml/pages/InstancePicker.qml#L76

Does not trigger for "Http" or "Https" all of which are likely inputs.

**Comment by poVoq** [comment]
Made a simple PR for it: https://github.com/dark-eye/pixelfed-web/pull/8

**Comment by dark-eye** [comment]
@poVoq Sorry it took along time.... 
It seems to work correctly 

 thank you very much :+1:
